### PR TITLE
W3 - Oct-8-2024

### PR DESCRIPTION
**Pull request by w3creatives**
Following issues are address in this PR:

#589 (additional fixes)
#590
#591 
#592 
#594 
#595 
#596 
#597
#600 
#603 
#604 
#605 
#606 
#612

### CODE REVIEW

**Comment by leeomara** [comment]
The readme say to run `migrate_initial_and_update.sh`, but I can only find `migrate_initial_and_update_w3.sh`. Should that file be renamed, or the readme changed?

**Comment by w3creatives** [comment]
That was a typo.  I prefer to change it in the readme file in the next PR.

**Comment by leeomara** [comment]
I appreciate the updated and expanded instructions. Is the omision of `[root-URL]/custom_migrate` from the numbered steps intentional? Is that step still required?

**Comment by w3creatives** [comment]
It is still there under "Post-import cleanup".

**Pull request merged**
