### PR TITLE
W3 main d10 working sep 13 2024

### PR DESCRIPTION
**Pull request by w3creatives**

### CODE REVIEW

**Comment by leeomara** [comment]
@w3creatives can you explain why 317f561189 adds the comment_notify module? That module now seems to be causing site crashes in a few places (e.g. when editing a user).

**Comment by w3creatives** [comment]
It was there in this PR:

https://github.com/ytgov/yukon-ca/pull/577/files

**Comment by w3creatives** [comment]
It was there in this PR:

https://github.com/ytgov/yukon-ca/pull/577/files

**Comment by leeomara** [comment]
Thanks for pointing me in the right direction.

**Pull request merged**
