### PR TITLE
Issue #144 - Opener description

### PR DESCRIPTION
**Pull request by w3creatives**
**Issue Addressed:** 
https://github.com/ytgov/yukon-ca/issues/144

**Steps:**
1. Update the file.
2. Run the **drush cim -y** command.
3. Clear Drupal cache using **drush cr**.

### CODE REVIEW

**Comment by ew-andrew-sus** [comment]
check if you need a new field for this, please
Seems that a body field is used in D10 instead of field_opener_description
image

**Comment by w3creatives** [comment]
Hi Andrew,

We have revised it as requested.

Thanks,

**Comment by ew-andrew-sus** [comment]
@w3creatives According to the current implementation, you have to rename Body -> Opener description

**Comment by w3creatives** [comment]
Correct. Somehow, missed one file.

**Pull request merged**
